### ISSUE TITLE
Dealing with multiple instances

### ISSUE THREAD

**Issue by chrislema** [Prospress/woocommerce-subscriptions-gifting#134]
If I add a single instance of a subscription to my cart, I can then mark it as a gift. I then can put in an email. After that, I can repeat the action. Multiple times.

But if I simply add it once, and then update the quantity to "3", for example, I am not able to get three text boxes for the gifted subscriptions.

**Comment by thenbrent** [comment]
Welcome @chrislema! The quantity input shown next to the cart item is for increasing the quantity of that cart item rather than adding new cart items for the same product.

There is a valid use case for increasing the quantity of an item. For example, if I added a monthly box of Cohibas to the cart which I am gifting to you, but then decide I should be far more generous than that, so want to change it to send you 3 boxes per month (same product, same recipient, just more Cohibas).

I can see why that UI is confusing though, especially if coming at it from a memberships perspective, where you almost never want a customer to have more than one of that product/cart item.

For that case, you could use the _Sold Individually_ flag on the product (this checkbox https://cloudup.com/caMrLGELQqy), and then the quantity inputs won't be displayed on the cart (or product page).

The buyer can still add more than one of that subscription product to the cart, from the product page, as long as each has a different recipient, (e.g. cart page https://cloudup.com/ckCiAOp1J9N for a product marked _Sold Individually_ but with two different recipients).

Does that work for you? 😄

**Comment by chrislema** [comment]
Yup, that's great.

**Comment by thenbrent** [comment]
Closing this one out then. 😄
