### ISSUE TITLE
Memberships Integration Broken?

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#140]
From comment here: https://github.com/Prospress/woocommerce-subscriptions-gifting/issues/103#issuecomment-216948801

> Hello! Thanks for creating this! Have you tested if the integration with Memberships still works in the last version of WP and WooCommerce? It stopped working after I updated. Ir creates the users, but not the membership.

**Comment by thenbrent** [comment]
Hi @EneHacheCe thanks for the report. We'll double check nothing has been broken by the latest versions. Could you please also copy/paste your site's System Status report in a comment on this issue?

You can learn more about how to find the System Status report here: https://docs.woothemes.com/document/understanding-the-woocommerce-system-status-report/

You can remove anything from that you don't want to share, we mainly need to see which versions of plugins you have active and what other plugins are active.

**Comment by james-allan** [comment]
Hi @EneHacheCe. 

Sorry for the trouble you're having with Memberships integration, I've just double checked that purchasing a membership for a recipient still works with the latest version of Memberships, Subscriptions, WooCommerce and WordPress. I'll need further information in order to diagnose what's preventing the membership from being created. In addition to the system status report (or plugins and version numbers) could you please:
- check your sites error log to see if there're any errors occurring during the checkout process
- explain the subscription product tied to the membership that is being purchased
 - is it a standard subscription or variable subscription?
 - does the subscription product have a trial period, end date, sign up fee, is synced?
- when purchasing the membership, were there other membership products in the cart or was it just 1 membership product? Multiple memberships can be purchased in the one order but this could help in narrowing down what is happening 😄

**Comment by thenbrent** [comment]
Hi @EneHacheCe I'm going to close this now as we haven't heard back from you or been able to reproduce the issue.

Please reopen it though if you are still experiencing the issue.
