### ISSUE TITLE
Way to add more email fields for a group gifted subscription? 

### ISSUE THREAD

**Issue by jiwicky** [Prospress/woocommerce-subscriptions-gifting#143]
If I wanted to set up a product that is 5x (min quantity) a certain subscription, the subscriptions 2.0 plugin counts that as one item and therefore it's in the cart as one single item. It would be great if the purchaser of this product had 5x email fields when ticking the 'this is a gift' box and this plugin could take care of creating those accounts / sending emails x5 for those addresses. 

I saw the other  (#134)  that is similar to this, but the solution for that would not be the solution for this. 

If there's a way to do this based on funcs or hooks, I didn't find it and would love some direction if there's already a way to do it.

**Comment by thenbrent** [comment]
hey @jiwicky, there is the `html-add-recipient.php` template which you can override. But that would only allow you to add 5 email fields to the one line item, which isn't what you want. You want up-to 5 different line items (because there are up-to 5 different recipients for the same product).

What are you using to enforce the 5x minimum quantity limit?

I think either whatever is handling that or some custom code would be required to split each subscription out whenever a recipient is being added.

If it enforces it at the cart level rather than the product level, it's possibly already possible to handle this by adding more of the same product to the cart (potentially with different recipients), then setting the quantity of that in the cart.

But that's not great UX. Coming up with good UX/UI to handle this will be really hard.

For example, what if the store owner wants to gift 2x of the subscription product to someone, but receive 3x themselves? Or Gift 1x to one person, 1x to another, 1x to another, and 2x to themselves?

At a minimum, you'd need something that:

* enforced a min-quantity of the product when adding to the cart (sounds like you have this already)
* either automatically splits line items in the cart whenever a recipient is added to that line item, or perhaps adds a button to "add different recipient" or something which splits the line item and allows them to enter a new recipient for a certain quantity of that line item
* checks the cart to make sure that the total quantity of the product is never allowed to go below the minimum quantity regardless of how many line items there are for different recipients.

Definitely a unique use case and not something we've considered for Gifting itself. It would need to be custom or handled in the plugin which enforces minimum quantities IMO as I don't think it makes sense for us to implement in the Gifting plugin.

**Comment by jiwicky** [comment]
Hi @thenbrent - thanks for the quick response. We're using the woo min/max quanities plugin to put a min quantity in this product. Min quantity is set in the admin end under the product ui. So the user (purchaser) has the option to go up from 5, but not down. We only offer one subscription type - It's basically a wall in front of content on the site, not a physical product subscription, so I wouldn't have to worry about handling different types. 

I've overridden the html-add-recipient template for other things already (to hide the gifting box on this particular product so the ui won't be confusing to users), so that's at least a foot in the door with this. 

So if I did find a way to show 5 or any other amount of email fields under the one product without splitting them up, would it be this plugin's default behavior to handle each of those and send out emails / create accounts for each when checkout is complete the same way that it does one? Or would the way that this product is grouped as one line item break the functionality? 

I've tooled around a lot with the default behavior of products, etc and it doesn't seem like I can add 1 product 5 times to get the fields there, because woo subscriptions would just lump them together. I've look through the docs over there and couldn't find a way to split them back up. I'll keep thinking / researching on it. 

I understand why you wouldn't feel the need to roll functionality for this case into core of the plugin, but thanks a ton for helping me begin to wrap my head around the problem / approach here.

**Comment by thenbrent** [comment]
> would it be this plugin's default behavior to handle each of those

No. Gifting only allows each line item to have one recipient so it will only create one subscription/send one email etc. for each line item.

> I've tooled around a lot with the default behavior of products, etc and it doesn't seem like I can add 1 product 5 times to get the fields there, because woo subscriptions would just lump them together.

Yeah, the normal WC/Subscriptions behaviour is to increase the quantity of the same product, not to add a new line item for it.

You can use the `'woocommerce_add_cart_item_data'` filter to set your own custom line item meta though to split the same product into separate line items. That's what Gifting uses to make sure the same product with a different recipient will be a different line item.

**Comment by jiwicky** [comment]
This is great to get started with @thenbrent - thanks for your time and pointing me in the direction of that filter - it helps a lot. Awesome plugin!

**Comment by thenbrent** [comment]
Glad I could help @jiwicky. I'll close this one now. 😄
