### ISSUE TITLE
Prepaid gift option: Pay for whole time in advance and be done

### ISSUE THREAD

**Issue by jnachtigall** [Prospress/woocommerce-subscriptions-gifting#158]
Could not find some other place, so I leave this here. 

I think for a gift option the ability that the purchaser can pay the subscription in advance is pretty obvious. Like do it once and then be done without any further hassle for purchaser and receiver. Think of a 3 months coffee subscription. The following things come to my mind that this plugin does not seem to support atm:

- [ ] Prepaid option: As a purchaser I pay for the whole 3 deliveries in advance, i.e. say once 30 € instead of 3 x 10 € each month
- [ ] Anti-Spoiler: I do not want that there's an email sent to the receiver because it's a present/gift. I want to give it to the person, I want to surprise the receiver, I do not want this to be spoiled by an automatic email
- [ ] i don not know what's the plan here, but installing something from trunk directly isn't something I'd prefer for a webshop. So putting this on wordpress.org/plugins and using semantic versioning would be appreciated.

Just some feedback from my use case (which is coffee subscription), feel free to ignore :)

**Comment by thenbrent** [comment]
Hi @jnachtigall, I've read over your 3 suggestions and agree all of those things would be valuable additions. If you are a developer or have a developer on your team, we'd welcome pull requests and can work to add those features with them. Otherwise, I'll keep a note of these feature requests (it's not the first time we've seen most of them) and we may add them in the future. As a 100% free plugin, I'm sure you can understand feature development on it is slower than commercial plugins and relies as much on community contributions as our own efforts.

> Prepaid option: As a purchaser I pay for the whole 3 deliveries in advance, i.e. say once 30 € instead of 3 x 10 € each month

That is already possible, you can create a subscription product in a certain way to achieve it. Some more details [here](https://docs.woocommerce.com/document/subscriptions/faq/#section-66). Once you have a product setup like that, the purchaser can choose that option for the gift if they want to prepay.

> i don not know what's the plan here, but installing something from trunk directly isn't something I'd prefer for a webshop.

We'll be "officially launching" it eventually. For now, we've decided to open it up on GitHub as a "soft launch" as GitHub gives us more freedom in working with feedback/code before we decide on how to officially release it (which may be wordpress.org or may be commercially).
