### ISSUE TITLE
WooCommerce 3.0 Compatibility

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#203]
Once we finish getting Subscriptions stable with WooCommerce 3.0, we need to update Gifting to handle all the changes in 3.0 too.

**Comment by colemast2001** [comment]
I am getting this same error after updating. If there is any work around for this please let me know. It stops the membership account from being created and linking to the subscription. 
Thanks.

**Comment by nburch** [comment]
Same here! "Gifting" a subscription is not functioning properly after 3.0 update. We are using Subscriptions with Memberships. The subscription is created just fine and all emails fire off properly but the corresponding membership does not get created and linked to the subscription.

**Comment by sjradmin** [comment]
I am having the same issue also if a purchaser is not having a subscription the gift subscription order doesn't go through it seems. Any update on this error?

Warning: Declaration of WCSG_Email_Completed_Renewal_Order::trigger($order_id) should be compatible with WCS_Email_Completed_Renewal_Order::trigger($order_id, $order = NULL)

**Comment by thenbrent** [comment]
@sjradmin we hope to get to 3.0 compatibility work soon. I'm very sorry for the delay and trouble this is causing you.

**Comment by sjradmin** [comment]
Hi Brent,

What's the ETA for it?

**Comment by thenbrent** [comment]
@sjradmin if I had an ETA I'd have given it instead of just saying "soon". :)

**Comment by sjradmin** [comment]
Ok, Thanks
Btw I am on Wordpress Version 4.8
Just a general question about the plugin which might be just due to the compatibility error we are facing. Is the buyer of the gift must have a subscription with us in order to gift one to others?I don't think so but my site admin is saying we had cases like that which someone bought it as a gift and the recipient never received it. Might be just emailing did not go through due to this bug?

 

    On Friday, 28 July 2017, 9:29, Brent Shepherd <notifications@github.com> wrote:
 

 @sjradmin if I had an ETA I'd have given it instead of just saying "soon". :)—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by thenbrent** [comment]
> Might be just emailing did not go through due to this bug?

Most likely. The purchaser doesn't need to have an existing subscription prior to gifting one.

**Comment by sjradmin** [comment]
Actually, it seems that email went through but we had to add the subscription for the recipient manually so that's what we think if a buyer is not having a subscription he/she can not gift one it seems. 

    On Friday, 28 July 2017, 9:46, Brent Shepherd <notifications@github.com> wrote:
 

 
Might be just emailing did not go through due to this bug?
Most likely. The purchaser doesn't need to have an existing subscription prior to gifting one.—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by james-allan** [comment]
> we had to add the subscription for the recipient manually so that's what we think if a buyer is not having a subscription he/she can not gift one it seems.

Oh ok. We'll look into that possibility when we get to working on WC 3.0 compatibility. It's definitely not the intention.

**Comment by james-allan** [comment]
### WC 3.0 Testing Checklist:

- [ ] Adding recipient to cart item via:
   - [ ] Single product page
   - [ ] Cart item
   - [ ] Checkout
- [ ] Cart item displays recipient fields:
  - [ ] on checkout
  - [ ] in cart
  - [ ] in mini-cart
- [ ] Recipient account created after checkout (where no user already exists)
- [ ] Recipient granted management [permissions](https://github.com/Prospress/woocommerce-subscriptions-gifting#shared-subscription-management)
  - [ ] View Subscription 
  - [ ] Suspend Subscription 
  - [ ] Reactivate Subscription 
  - [ ] Cancel Subscription 
  - [ ] Change Shipping Address 
  - [ ] Change Payment Method 
  - [ ] Manually Renew 
  - [ ] Resubscribe
  - [ ] Switch (upgrade/downgrade)
  - [ ] View Parent Orders
  - [ ] View Renewal Orders 
- [ ] Recipient granted with the gifted subscription downloads
 - [ ] Purchaser granted downloads when applicable (https://cloudup.com/c1mieSx89gM) 
- [ ] Emails
  - [ ] New Recipient Account
  - [ ] New Initial Order
  - [ ] Processing Renewal Order
  - [ ] Completed Renewal Order
- [ ] Ensure download links are for the correct user
  - [ ] My account pages (logged in user)
  - [ ] Emails (email recipient)
- [ ] New recipient details collection page (https://github.com/Prospress/woocommerce-subscriptions-gifting#recipient-account-creation)
- [ ] Subscription & Order line items display recipient meta
  - [ ] Customer facing emails and my account pages
  - [ ] Admin facing edit subscription and order screens
- [ ] Processing renewals 
  - [ ] Automatic 
  - [ ] Manual
- [ ] Resubscribe
- [ ] WooCommerce Memberships integration

**Comment by sjradmin** [comment]
Is the new release ready ?

**Comment by seb86** [comment]
@sjradmin Looks very close. I hope to try this out for the first time myself. Looking forward to the last checkbox to be ticked.

**Comment by james-allan** [comment]
> Is the new release ready ?
@sjradmin not quiet yet. There's just a bit more testing to do. 

In regards to your previous report about recipients not being added to subscriptions etc, while testing I haven't seen anything of that nature. Once I've finalised testing and the next version is released we'll have to see if that behaviour continues for you before we dig deeper.

**Comment by sjradmin** [comment]
Any update? 

    On Wednesday, 2 August 2017, 10:27, James Allan <notifications@github.com> wrote:
 

 
Is the new release ready ?
@sjradmin not quiet yet. There's just a bit more testing to do.
In regards to your previous report about recipients not being added to subscriptions etc, while testing I haven't seen anything of that nature. Once I've finalised testing and the next version is released we'll have to see if that behaviour continues for you before we dig deeper.—

**Comment by james-allan** [comment]
@sjradmin We've merged the WC 3.0 compatibility fixes with #211. It just hasn't been officially released yet. 

We've got a couple of other fixes (#213, #214, #181) that we want to get into the next release before we release the next version. Currently, the plan is to release in the next 2 weeks. 

If you can't wait any longer you can always download the most recent version of `master` as it already contains WC 3.0 compatibility. You can download it from this link: https://github.com/Prospress/woocommerce-subscriptions-gifting/archive/master.zip

Sorry for the delay. 

Now that #211 has been released, I'm going to close this one.

**Comment by sjradmin** [comment]
Hi
I downloaded the latest filed and replaced the old ones one on our site but still the error is showing up:
Warning: Declaration of WCSG_Email_Completed_Renewal_Order::trigger($order_id) should be compatible with WCS_Email_Completed_Renewal_Order::trigger($order_id, $order = NULL) in /home/wp_7ixq2i/xxxxxxxxxxx/wp-content/plugins/woocommerce-subscriptions-gifting-master/includes/emails/class-wcsg-email-completed-renewal-order.php on line 63

Warning: Declaration of WCSG_Email_Processing_Renewal_Order::trigger($order_id) should be compatible with WCS_Email_Processing_Renewal_Order::trigger($order_id, $order = NULL) in /home/wp_7ixq2i/xxxxxxxxxxx/wp-content/plugins/woocommerce-subscriptions-gifting-master/includes/emails/class-wcsg-email-processing-renewal-order.php on line 60
 

    On Friday, 1 September 2017, 10:17, James Allan <notifications@github.com> wrote:
 

 @sjradmin We've merged the WC 3.0 compatibility fixes with #211. It just hasn't been officially released yet.We've got a couple of other fixes (#213, #214, #181) that we want to get into the next release before we release the next version. Currently, the plan is to release in the next 2 weeks.If you can't wait any longer you can always download the most recent version of master as it already contains WC 3.0 compatibility. You can download it from this link: https://github.com/Prospress/woocommerce-subscriptions-gifting/archive/master.zipSorry for the delay.Now that #211 has been released, I'm going to close this one.—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by james-allan** [comment]
@sjradmin please check your files again. The declaration of `WCSG_Email_Completed_Renewal_Order::trigger()` in the latest version is correct and those errors you're getting shouldn't be happening if you have the latest version of the plugin installed.

I've attached the latest version of the plugin below: 
[woocommerce-subscriptions-gifting.zip](https://github.com/Prospress/woocommerce-subscriptions-gifting/files/1617242/woocommerce-subscriptions-gifting.zip)

**Comment by sjradmin** [comment]
Hi
I replaced the files again but still error showing up at the end of the purchase process and the membership was not linked to the gifted user account and I had to link it manually. So there is still some issues with the plugin. 

    On Wednesday, 10 January 2018, 12:44, James Allan <notifications@github.com> wrote:
 

 @sjradmin please check your files again. The declaration of WCSG_Email_Completed_Renewal_Order::trigger() in the latest version is correct and those errors you're getting shouldn't be happening if you have the latest version of the plugin installed.I've attached the latest version of the plugin below:
woocommerce-subscriptions-gifting.zip—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |

**Comment by james-allan** [comment]
@sjradmin could you send me a copy of the Gifting extension active on your site, please?

Could you also confirm that it's these issues which are still happening: 

```
Warning: Declaration of WCSG_Email_Processing_Renewal_Order::trigger($order_id)
```

**Comment by sjradmin** [comment]
Hi James
Well it's exactly the file you have sent me in previous email. I just unzipped and copied to the server to replace. 

    On Thursday, 1 February 2018, 10:51, James Allan <notifications@github.com> wrote:
 

 @sjradmin could you send me a copy of the Gifting extension active on your site, please?Could you also confirm that it's these issues which are still happening:Warning: Declaration of WCSG_Email_Processing_Renewal_Order::trigger($order_id)
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.  

   

|  | Virus-free. www.avast.com  |
