### ISSUE TITLE
Form doesn't remember what is filled out - also UX issue

### ISSUE THREAD

**Issue by CHEWX** [Prospress/woocommerce-subscriptions-gifting#216]
Hi,

Nice plugin.

By default, when you add in email on the subscription single page and click sign up. When you go to cart, it's empty. Now in cart view, you fill out the email again, then click checkout. Then when you go to checkout, the gift option is empty and the email empty again. You now have to click and fill out 3 times. Once you click pay on the submit page it works.

My current work around is to remove from the subscription single and cart and display only on checkout. 

Thinking about it, I don't see the point in outputting on single and cart pages as you can only have 1 gift per order as there is only 1 shipping form... unless I am missing something.

Thanks,
Tom

**Comment by james-allan** [comment]
Hi @CHEWX 

Thanks for the questions. 

> By default, when you add in email on the subscription single page and click sign up. When you go to cart, it's empty...

It sounds like your store is having issues storing cart item data. This is definitely not the expected behaviour and I suspect it's some plugin or theme conflict. Could you activate a default theme and deactivate all plugins except WooCommerce, Subscriptions and Subscriptions Gifting and see if that fixes the issue. 

If you are running WooCommerce 3.0 you could also download the 3.0 compatible version of the plugin (from [here](https://github.com/Prospress/woocommerce-subscriptions-gifting/archive/master.zip)) to see if that fixes the issue.

If you are still experiencing the same issues after exhausting both possible fixes, please send me (james@prospress.com) your PHP error logs and I'll see if there's an error in there which indicates why this is happening.

>  I don't see the point in outputting on single and cart pages as you can only have 1 gift per order as there is only 1 shipping form... unless I am missing something.

There are circumstances where you can have more than one gift per checkout. If for example you're selling virtual goods where no shipping is required. There are also plugins which allow your customers to ship to multiple addresses per checkout - [Shipping Multiple Addresses](https://woocommerce.com/products/shipping-multiple-addresses/) for example.

**Comment by CHEWX** [comment]
Thanks for your reply @james-allan 

I think this can be closed. As the issue makes sense.
