### ISSUE TITLE
Blank email subject and heading on customer_completed_order notification emails

### ISSUE THREAD

**Issue by Shotster** [Prospress/woocommerce-subscriptions-gifting#226]
The order completion notification email sent to customers contains a **blank subject line and heading** with this plugin installed. It seems the flag set in this function...

https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/4245f0f0ec4ed5334713c8cde3226e18b16120f0/includes/class-wcsg-email.php#L255

...causes the following function...

https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/4245f0f0ec4ed5334713c8cde3226e18b16120f0/includes/class-wcsg-email.php#L218

...to return an empty string.

This occurs after purchasing a simple virtual product (_not_ downloadable).

**EDIT**: I don't know if it's relevant, but I do have the [WooCommerce Order Status Control plug-in](https://woocommerce.com/products/woocommerce-order-status-control/) installed as well, and it's configured to auto-complete orders for virtual products.

**Comment by james-allan** [comment]
Hi @Shotster 
Thanks for the report. 

I've been able to replicate this with: 

**WooCommerce Subscriptions:** 2.2.12
**WooCommerce:** 3.1.2
**WCS Gifting:** `master`

To replicate: 

1. Make sure dual download permissions are disabled from **WooCommerce > Settings > Subscriptions (tab)** (https://cloudup.com/c5ZYcl5aukt)
1. Create a subscription product which is downloadable and virtual with downloadable files
2. Purchase the product entering a recipient email during the cart/checkout process

Once the order is complete you should receive an email sent to the purchaser with a blank subject and heading eg: 

![86rfubycyp](https://user-images.githubusercontent.com/8490476/31373574-f03e08cc-addd-11e7-97ec-f34e10cffc0d.png). 

The issue is coming from this [line](https://github.com/Prospress/woocommerce-subscriptions-gifting/blob/master/includes/class-wcsg-email.php#L245) it appears. 

IIRC that line is supposed to reformat the email heading and subject sent to purchasers so that it doesn't say "Download your files" when they have had those permissions stripped and given to the recipient.

It looks like WC in 3.0, removed the "download your files" part and so this function may be redundant now. 

Thanks again for the report @Shotster. We'll see if we can get this fixed up for you.

**Comment by Shotster** [comment]
> Create a subscription product which is downloadable and virtual with downloadable files

Thanks, @james-allan

I would only add the following points:

 1. In my case, the subscription is NOT downloadable. 
2.  The item purchased does not have to be the subscription itself.  The issue occurs for me when I purchase another, unrelated, virtual product.

**Comment by james-allan** [comment]
> I would only add the following points:

👍 There are probably a large number of ways to replicate it, I've just listed the way I was able to replicate it for future reference. They are all caused by the same bug though so fixing one will fix it for all cases.

Looking at the function causing this issue, it would essentially be any completed order email where the customer doesn't have any downloadable files attached to the order which would get a blank subject and heading.

**Comment by akasapriya** [comment]
Hi @james-allan 

Just to add to this, I can replicate the issue on 
woocommerce 3.2.1
wc subscriptions 2.2.13

And it seems to occur on all completed order emails including those that contain links to downloadable files. I hope that's helpful. 

Do you have an idea of when you might be able to get this fixed? If you need more info about my setup I'm happy to help.
