### ISSUE TITLE
Duplicate endpoint fields

### ISSUE THREAD

**Issue by thenbrent** [Prospress/woocommerce-subscriptions-gifting#247]
While working on https://github.com/Prospress/woocommerce-subscriptions/pull/2533, I noticed that the **WooCommerce > Settings > Accounts** screen had duplicate account endpoint fields for **Subscriptions** and the **View subscription** endpoint.

![](https://cl.ly/3i1k0B0M133w/Screen%20Shot%202018-02-02%20at%204.27.48%20pm.png)

I quickly tried disabling/enabling a few Subscriptions related mini-extensions to see if any of those were the culprit, and disabling Gifting removed the duplicates.

This only happens with `master` of Subscriptions. It doesn't happen with the latest public version, v2.2.17. So it's likely related to https://github.com/Prospress/woocommerce-subscriptions/pull/2511 / https://github.com/Prospress/woocommerce-subscriptions/pull/2533.

**Comment by james-allan** [comment]
I've done some quick digging into this and this is happening because the `WCSG_Query` extends the `WCS_Query` class and calls the parent constructor. So you end up with 2 callbacks attached for all hooks added in [`WCS_Query:: __construct `](https://github.com/Prospress/woocommerce-subscriptions/blob/2.2.17/includes/class-wcs-query.php#L10-L32)
