### ISSUE TITLE
Option to gift not working on WC 3.4

### ISSUE THREAD

**Issue by james-allan** [Prospress/woocommerce-subscriptions-gifting#269]
While working on GDPR stuff this morning I noticed the gifting fields are behaving strangely and are essentially broken on some pages. 

- [x] Duplicate fields being displayed on variable product pages: https://cloudup.com/cakjvVJ8bR7. _Simple products appear fine (https://cloudup.com/cOzs1Rk_M53)_. PR submitted to WCS core to fix this one (https://github.com/Prospress/woocommerce-subscriptions/pull/2706)
- [x] Blocked fields on the cart page: https://cloudup.com/cg6HbmpwFOJ. The checkbox is also gone.

Checkout looks fine (https://cloudup.com/c5lMewoz4Yj).

**Comment by james-allan** [comment]
To fix the cart issue, I think I'll need to submit a change to WC core. The issue is that we were exploiting a bug essentially in WC by hooking onto the cart item title and attaching our HTML. 

They now escape the value returned by the `woocommerce_cart_item_name` after [this commit](https://github.com/woocommerce/woocommerce/commit/9d10d107e20e20b20719236bfbfd123f15667a3d#diff-97ddb272729b3ec92835746e11f935c1R79) and so the checkbox and checkbox get removed.

I've had a quick look around and I can't see an action hook that would work for us. To achieve the same placement, we could use the `woocommerce_get_item_data` filter. That's really just another hack though and wouldn't work anyway because it doesn't pass the order item key which gifting needs to print the HTML. So the only option I can see is to submit a PR to WC core adding an action about [here](https://github.com/woocommerce/woocommerce/blob/3.4.0/templates/cart/cart.php#L83).

**Comment by james-allan** [comment]
WC PR: https://github.com/woocommerce/woocommerce/pull/20190

**Comment by thenbrent** [comment]
Good diagnosis.

It is possible to workaround what's there within Gifting. You'd need to hook into one of the `wp_kses_` filters, and allow the elements being added by Gifting.

Let me know if you need more instruction than that. :)

FWIW, this is a breaking change, so in theory shouldn't have been included in 3.4. It's also a security issue, so from that perspective it _should_ have been included. Although based on other changes in that commit, it looks like it was added to please PHPCS, and I notice some filters are given a `// PHPCS: XSS ok` comment instead of being passed through `wp_kses_post()`, so I'm not sure what justified one vs. the other.
